// ----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version: v4.0.30319
//   Service Registry Version: 3.23.21180.1
//   Generated at: 2022-02-11T18:30:30
//
//   Changes to this file may cause incorrect behaviour and
//   will be lost if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------

using Ato.EN.ApplicationServices.Documents;
using Ato.EN.ApplicationServices.Serialization;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Ato.EN.Security.Authorisation.AM.Messaging.ICP
{
    /// <summary>
    /// CheckClientSecretsResponse document.
    /// </summary>
    [GeneratedCode("Ato.EN.ServiceRegistry", "3.23.21180.1")]
    [Serializable]
    [DataContract(Namespace = "Ato.RM.Documents/0")]
    public partial class CheckClientSecretsResponseDocument : InteractionDocument
    {
        #region Declarations

        [DataMember(Name = "QuestionAnswerResult")]
        private string _questionAnswerResult;

        #endregion

        #region Constructors

        /// <summary>
        /// Initialises a new CheckClientSecretsResponseDocument instance.
        /// </summary>
       
        public CheckClientSecretsResponseDocument()
        { }

        /// <summary>
        /// Initialises a new CheckClientSecretsResponseDocument instance populating the header
        /// details from the given document.
        /// </summary>
        /// <param name="headerSource">The document to copy the header details from.
        /// </param>
        public CheckClientSecretsResponseDocument(InteractionDocument headerSource)
            : base(headerSource)
        { }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the QuestionAnswerResult.
        /// </summary>
        /// <value>The QuestionAnswerResult.</value>
        [CopyBookProperty("QA-RESULT",  10, Order=2)]
        public string QuestionAnswerResult
        {
            get { return _questionAnswerResult; }
            set { _questionAnswerResult = value; }
        }

        #endregion
    }
}
