// ----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version: v4.0.30319
//   Service Registry Version: 3.23.21180.1
//   Generated at: 2022-02-11T18:30:30
//
//   Changes to this file may cause incorrect behaviour and
//   will be lost if the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------

using Ato.EN.ApplicationServices.Documents;
using Ato.EN.ApplicationServices.Serialization;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Ato.EN.Security.Authorisation.AM.Messaging.ICP
{
    /// <summary>
    /// CheckClientSecretsRequest document.
    /// </summary>
    [GeneratedCode("Ato.EN.ServiceRegistry", "3.23.21180.1")]
    [Serializable]
    [DataContract(Namespace = "Ato.RM.Documents/0")]
    public  class CheckClientSecretsRequestDocument : InteractionDocument
    {
        #region Declarations

        [DataMember(Name = "ChannelType")]
        private int _channelType;
        [DataMember(Name = "ClientExternalId")]
        private string _clientExternalId;
        [DataMember(Name = "ClientExternalIdType")]
        private int _clientExternalIdType;
        [DataMember(Name = "SecretQuestionAnswerCount")]
        private int _secretQuestionAnswerCount;
        [DataMember(Name = "SecretQuestionAnswers")]
        private List<SecretQuestionAnswersDocument> _secretQuestionAnswers;

        #endregion

        #region Constructors

        /// <summary>
        /// Initialises a new CheckClientSecretsRequestDocument instance.
        /// </summary>
       
        public CheckClientSecretsRequestDocument()
        { }

        /// <summary>
        /// Initialises a new CheckClientSecretsRequestDocument instance populating the header
        /// details from the given document.
        /// </summary>
        /// <param name="headerSource">The document to copy the header details from.
        /// </param>
        public CheckClientSecretsRequestDocument(InteractionDocument headerSource)
            : base(headerSource)
        { }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the ChannelType.
        /// </summary>
        /// <value>The ChannelType.</value>
        [CopyBookProperty("CHANNEL-TYPE-CODE", 3, Order=2)]
        public int ChannelType
        {
            get { return _channelType; }
            set { _channelType = value; }
        }

        /// <summary>
        /// Gets or sets the ClientExternalId.
        /// </summary>
        /// <value>The ClientExternalId.</value>
        [CopyBookProperty("CLIENT-EXTERNAL-ID", 255, Order=3)]
        public string ClientExternalId
        {
            get { return _clientExternalId; }
            set { _clientExternalId = value; }
        }

        /// <summary>
        /// Gets or sets the ClientExternalIdType.
        /// </summary>
        /// <value>The ClientExternalIdType.</value>
        [CopyBookProperty("CLIENT-ID-TYPE", 3, Order=4)]
        public int ClientExternalIdType
        {
            get { return _clientExternalIdType; }
            set { _clientExternalIdType = value; }
        }

        /// <summary>
        /// Gets or sets the SecretQuestionAnswerCount.
        /// </summary>
        /// <value>The SecretQuestionAnswerCount.</value>
        [CopyBookProperty("SECRET-QUESTION-COUNT", 2, Type = CopyBookType.UInteger, Order=5)]
        public int SecretQuestionAnswerCount
        {
            get { return _secretQuestionAnswerCount; }
            set { _secretQuestionAnswerCount = value; }
        }

        /// <summary>
        /// Gets or sets the SecretQuestionAnswers.
        /// </summary>
        /// <value>The SecretQuestionAnswers.</value>
        [CopyBookPropertyGroup("SECRET-QUESTION-ANSWER-GRP",10, "SecretQuestionAnswerCount", Order=6)]
        public List<SecretQuestionAnswersDocument> SecretQuestionAnswers
        {
            get
            {
                if (_secretQuestionAnswers == null)
                {
                    _secretQuestionAnswers = new List<SecretQuestionAnswersDocument>();
                }
                return _secretQuestionAnswers;
            }
            set { _secretQuestionAnswers = value; }
        }

        #endregion

        #region Inner Classes

        /// <summary>
        /// SecretQuestionAnswers document.
        /// </summary>
        [Serializable]
        [DataContract(Namespace = "Ato.RM.Documents/0")]
        public partial class SecretQuestionAnswersDocument
        {
            #region Declarations

            [DataMember(Name = "SecretQuestionType")]
            private int _secretQuestionType;
            [DataMember(Name = "SecretQuestionCode")]
            private int _secretQuestionCode;
            [DataMember(Name = "AnswerText")]
            private string _answerText;

            #endregion

            #region Constructors

            /// <summary>
            /// Initialises a new SecretQuestionAnswersDocument instance.
            /// </summary>
            public SecretQuestionAnswersDocument()
            { }

            #endregion

            #region Properties

            /// <summary>
            /// Gets or sets the SecretQuestionType.
            /// </summary>
            /// <value>The SecretQuestionType.</value>
            [CopyBookProperty("QUESTION-TYPE", 2, Type = CopyBookType.UInteger, Order =1)]
            public int SecretQuestionType
            {
                get { return _secretQuestionType; }
                set { _secretQuestionType = value; }
            }

            /// <summary>
            /// Gets or sets the SecretQuestionCode.
            /// </summary>
            /// <value>The SecretQuestionCode.</value>
            [CopyBookProperty("QUESTION-CODE", 3, Order=2)]
            public int SecretQuestionCode
            {
                get { return _secretQuestionCode; }
                set { _secretQuestionCode = value; }
            }

            /// <summary>
            /// Gets or sets the AnswerText.
            /// </summary>
            /// <value>The AnswerText.</value>
            [CopyBookProperty("ANSWER-TEXT",  200, Order=3)]
            public string AnswerText
            {
                get { return _answerText; }
                set { _answerText = value; }
            }

            #endregion
        }

        #endregion
    }
}
